// source: grpc/helloworld.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.ai.sendy.victor.grpc.truckerlocation.Point', null, global);
goog.exportSymbol('proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply', null, global);
goog.exportSymbol('proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest.displayName = 'proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply.displayName = 'proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ai.sendy.victor.grpc.truckerlocation.Point = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ai.sendy.victor.grpc.truckerlocation.Point, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ai.sendy.victor.grpc.truckerlocation.Point.displayName = 'proto.ai.sendy.victor.grpc.truckerlocation.Point';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    orderId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    managerId: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest}
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest;
  return proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest}
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setOrderId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setManagerId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrderId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getManagerId();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * optional int64 order_id = 1;
 * @return {number}
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest.prototype.getOrderId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest} returns this
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest.prototype.setOrderId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 manager_id = 2;
 * @return {number}
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest.prototype.getManagerId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest} returns this
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationRequest.prototype.setManagerId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    truckerId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    point: (f = msg.getPoint()) && proto.ai.sendy.victor.grpc.truckerlocation.Point.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply}
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply;
  return proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply}
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTruckerId(value);
      break;
    case 2:
      var value = new proto.ai.sendy.victor.grpc.truckerlocation.Point;
      reader.readMessage(value,proto.ai.sendy.victor.grpc.truckerlocation.Point.deserializeBinaryFromReader);
      msg.setPoint(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTruckerId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getPoint();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.ai.sendy.victor.grpc.truckerlocation.Point.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 trucker_id = 1;
 * @return {number}
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply.prototype.getTruckerId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply} returns this
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply.prototype.setTruckerId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional Point point = 2;
 * @return {?proto.ai.sendy.victor.grpc.truckerlocation.Point}
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply.prototype.getPoint = function() {
  return /** @type{?proto.ai.sendy.victor.grpc.truckerlocation.Point} */ (
    jspb.Message.getWrapperField(this, proto.ai.sendy.victor.grpc.truckerlocation.Point, 2));
};


/**
 * @param {?proto.ai.sendy.victor.grpc.truckerlocation.Point|undefined} value
 * @return {!proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply} returns this
*/
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply.prototype.setPoint = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply} returns this
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply.prototype.clearPoint = function() {
  return this.setPoint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ai.sendy.victor.grpc.truckerlocation.TruckerLocationReply.prototype.hasPoint = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ai.sendy.victor.grpc.truckerlocation.Point.prototype.toObject = function(opt_includeInstance) {
  return proto.ai.sendy.victor.grpc.truckerlocation.Point.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ai.sendy.victor.grpc.truckerlocation.Point} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.sendy.victor.grpc.truckerlocation.Point.toObject = function(includeInstance, msg) {
  var f, obj = {
    latitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    longitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ai.sendy.victor.grpc.truckerlocation.Point}
 */
proto.ai.sendy.victor.grpc.truckerlocation.Point.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ai.sendy.victor.grpc.truckerlocation.Point;
  return proto.ai.sendy.victor.grpc.truckerlocation.Point.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ai.sendy.victor.grpc.truckerlocation.Point} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ai.sendy.victor.grpc.truckerlocation.Point}
 */
proto.ai.sendy.victor.grpc.truckerlocation.Point.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLatitude(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLongitude(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ai.sendy.victor.grpc.truckerlocation.Point.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ai.sendy.victor.grpc.truckerlocation.Point.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ai.sendy.victor.grpc.truckerlocation.Point} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ai.sendy.victor.grpc.truckerlocation.Point.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLatitude();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getLongitude();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
};


/**
 * optional double latitude = 1;
 * @return {number}
 */
proto.ai.sendy.victor.grpc.truckerlocation.Point.prototype.getLatitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ai.sendy.victor.grpc.truckerlocation.Point} returns this
 */
proto.ai.sendy.victor.grpc.truckerlocation.Point.prototype.setLatitude = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double longitude = 2;
 * @return {number}
 */
proto.ai.sendy.victor.grpc.truckerlocation.Point.prototype.getLongitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ai.sendy.victor.grpc.truckerlocation.Point} returns this
 */
proto.ai.sendy.victor.grpc.truckerlocation.Point.prototype.setLongitude = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


goog.object.extend(exports, proto.ai.sendy.victor.grpc.truckerlocation);
