/**
 * @fileoverview gRPC-Web generated client stub for ai.sendy.victor.grpc.echo
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v5.27.0-dev
// source: grpc/helloworld.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.ai = {};
proto.ai.sendy = {};
proto.ai.sendy.victor = {};
proto.ai.sendy.victor.grpc = {};
proto.ai.sendy.victor.grpc.echo = require('./helloworld_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ai.sendy.victor.grpc.echo.EchoServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ai.sendy.victor.grpc.echo.EchoServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ai.sendy.victor.grpc.echo.EchoRequest,
 *   !proto.ai.sendy.victor.grpc.echo.EchoResponse>}
 */
const methodDescriptor_EchoService_Echo = new grpc.web.MethodDescriptor(
  '/ai.sendy.victor.grpc.echo.EchoService/Echo',
  grpc.web.MethodType.UNARY,
  proto.ai.sendy.victor.grpc.echo.EchoRequest,
  proto.ai.sendy.victor.grpc.echo.EchoResponse,
  /**
   * @param {!proto.ai.sendy.victor.grpc.echo.EchoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ai.sendy.victor.grpc.echo.EchoResponse.deserializeBinary
);


/**
 * @param {!proto.ai.sendy.victor.grpc.echo.EchoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ai.sendy.victor.grpc.echo.EchoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ai.sendy.victor.grpc.echo.EchoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ai.sendy.victor.grpc.echo.EchoServiceClient.prototype.echo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ai.sendy.victor.grpc.echo.EchoService/Echo',
      request,
      metadata || {},
      methodDescriptor_EchoService_Echo,
      callback);
};


/**
 * @param {!proto.ai.sendy.victor.grpc.echo.EchoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ai.sendy.victor.grpc.echo.EchoResponse>}
 *     Promise that resolves to the response
 */
proto.ai.sendy.victor.grpc.echo.EchoServicePromiseClient.prototype.echo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ai.sendy.victor.grpc.echo.EchoService/Echo',
      request,
      metadata || {},
      methodDescriptor_EchoService_Echo);
};


module.exports = proto.ai.sendy.victor.grpc.echo;

